{
 "title": "ECS  Status Codes Microservices - Traefik",
 "description": "Visualize Traefik backend Metrics",
 "tags": [
  "traefik",
  "ecs",
  "docker",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": "label_values(backend)" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Header", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"traefik:8080\"}"
    }
   ]
  },
  {
   "title": "Number of 5** sent per backend per $interval",
   "type": "graph",
   "description": "The backends: $service",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_requests_total{code=~\"^[^234].*\", backend=~\"^backend.*\"}[$interval])) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  { "title": "Service: $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "repeat": "service" },
  {
   "title": "Status Code Count per $interval",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_requests_total{backend=~\"$service\"}[$interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_backend_request_duration_seconds_sum{backend=~\"$service\"}) / sum(traefik_backend_requests_total{backend=~\"$service\"}) * 1000",
     "legendFormat": "Average response time (ms)"
    }
   ]
  },
  {
   "title": "Requests per response time buckets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_request_duration_seconds_bucket{backend=~\"$service\"}[$interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}