{
 "title": "ECS All Microservices - Traefik",
 "description": "Visualize Traefik Metrics",
 "tags": [
  "prometheus",
  "traefik"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": "label_values(backend)" },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Average Response Time (ms)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(traefik_backend_request_duration_seconds_sum) / sum(traefik_backend_requests_total) * 1000"
    }
   ]
  },
  {
   "title": "Status code 200 Count $interval",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_requests_total{code=\"200\", backend!=\"backend1\"}[$interval])) "
    }
   ]
  },
  {
   "title": "3xx Count last $interval",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_requests_total{code=\"301\", backend!=\"backend1\"}[$interval])) "
    }
   ]
  },
  {
   "title": "5xx Error Count last $interval",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_requests_total{code=\"500\", backend!=\"backend1\"}[$interval])) "
    }
   ]
  },
  {
   "title": "401 Error Count last $interval",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_requests_total{code=\"401\", backend!=\"backend1\"}[$interval])) "
    }
   ]
  },
  {
   "title": "404 Error Count last $interval",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_requests_total{code=\"404\", protocol=\"http\", backend!=\"backend1\"}[$interval])) "
    }
   ]
  },
  {
   "title": "Total requests last $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_requests_total{protocol=\"http\", backend!=\"backend1\"}[$interval]))",
     "legendFormat": "{{http}}"
    },
    {
     "expr": "sum(increase(traefik_backend_requests_total{protocol=\"https\", backend!=\"backend1\"}[$interval]))",
     "legendFormat": "{{https}}"
    }
   ]
  },
  {
   "title": "Errors Status Codes Count $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_requests_total{protocol=\"http\", backend!=\"backend1\",code!=\"201\",code!=\"200\",code!=\"304\",code!=\"301\",code!=\"302\",code!=\"303\",code!=\"304\",code!=\"304\"}[$interval])) by (backend,method, code)",
     "legendFormat": "{{ backend }} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Requests by Status Code $interval",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_requests_total{protocol!~\"https\", backend!=\"backend1\"}[$interval])) by (backend, method, code) ",
     "legendFormat": "{{ backend }} {{method}} {{code}}"
    }
   ]
  },
  {
   "title": "Total of requests for microservice in $interval ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_requests_total{protocol=~\"http\", backend!=\"backend1\"}[$interval])) by (backend)",
     "legendFormat": "{{ backend }} "
    }
   ]
  },
  {
   "title": "Status code 200 by Microservice $interval",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_requests_total{code=\"200\" , backend!=\"backend1\"}[$interval])) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Status code 300 by Microservice $interval",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_requests_total{code=\"301\" , backend!=\"backend1\"}[$interval])) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Status code 404 by Microservice $interval",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_requests_total{code=\"404\" , backend!=\"backend1\"}[$interval])) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  },
  {
   "title": "Status code 401 by Microservice $interval",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_backend_requests_total{code=\"401\" , backend!=\"backend1\"}[$interval])) by (backend)",
     "legendFormat": "{{ backend }}"
    }
   ]
  }
 ]
}